homeassistant:
  # Name of the location where Home Assistant is running
  name: Gullstølsbotn
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 74
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables custom_ui
#customizer:
#  custom_ui: local

#customize_glob:
#  "*.*":
#    custom_ui_state_card: state-card-custom-ui  

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Update duckdns
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

# Ikea Trådfri
tradfri:

# iOS
ios:

# Map
map:

# Ekstern DB
recorder:
  db_url: !secret db_url

# Knapper i UI
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml

sensor: !include sensor.yaml
#scene: !include scene.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
