## Sensors
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - humidity
    - precipitation
    - windSpeed
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/rola-ha.duckdns.org/cert.pem | awk '{ print $NF }'"
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_5m
    - type: since_last_boot
#### Template - Batteri fra telefon
- platform: template
  sensors:
    ola_iphone_batteri:
      friendly_name: "Batteri Ola iPhone"
      unit_of_measurement: '%'
      value_template: >-
            {%- if states.device_tracker.ola_iphone.attributes.battery %}
                {{ states.device_tracker.ola_iphone.attributes.battery|round }}
            {% else %}
                {{ states.sensor.ola_iphone_batteri.state }}
            {%- endif %}

# Speedtest
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
